// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7HNxohQz_Dh_Bbu1FRG4bY_5FjWJ_HSc',
    appId: '1:487457702310:web:00251ab1fae268baaf8f67',
    messagingSenderId: '487457702310',
    projectId: 'ucp-app-new',
    authDomain: 'ucp-app-new.firebaseapp.com',
    storageBucket: 'ucp-app-new.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRDVExIyN-3rhR-4VnRa3dvgQE2Xzht5c',
    appId: '1:487457702310:android:2e4583f81208e310af8f67',
    messagingSenderId: '487457702310',
    projectId: 'ucp-app-new',
    storageBucket: 'ucp-app-new.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyTutTCNrU5EJ5Mq1rWAqBEnED1J64KO0',
    appId: '1:487457702310:ios:a93afae32c564091af8f67',
    messagingSenderId: '487457702310',
    projectId: 'ucp-app-new',
    storageBucket: 'ucp-app-new.firebasestorage.app',
    iosBundleId: 'meme.ucpksa.ucp',
  );

}