// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVVSkxbBiyHFGWgc0IRhfP7txV14jTqQE',
    appId: '1:1062417228433:web:00251ab1fae268baaf8f67',
    messagingSenderId: '1062417228433',
    projectId: 'ucp-app-d8c23',
    authDomain: 'ucp-app-d8c23.firebaseapp.com',
    storageBucket: 'ucp-app-d8c23.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVVSkxbBiyHFGWgc0IRhfP7txV14jTqQE',
    appId: '1:1062417228433:android:86bea6af22e16ea2165530',
    messagingSenderId: '1062417228433',
    projectId: 'ucp-app-d8c23',
    storageBucket: 'ucp-app-d8c23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVVSkxbBiyHFGWgc0IRhfP7txV14jTqQE',
    appId: '1:1062417228433:ios:a93afae32c564091af8f67',
    messagingSenderId: '1062417228433',
    projectId: 'ucp-app-d8c23',
    storageBucket: 'ucp-app-d8c23.firebasestorage.app',
    iosBundleId: 'khp.ucpksa.com',
  );
}
